version: '3.8'

services:
  web:
    build: .
    image: rest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
      - .flaskenv
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:7.0.2
    container_name: redis_container
    ports:
      - "6379:6379"

  rq_worker:
    build: .
    command: sh -c "rq worker -u redis://redis:6379 emails"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis